<<<<<<< HEAD
[build]
  command = "ng build"
  publish = "dist/weather-app"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

=======
[build]
  command = "ng build"
  publish = "dist/weather-app"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

>>>>>>> 24ceb9179479bc97d1408d9e774c81f2154bc880
